"""Canonical parcel identity and source-record schemas.

ULPIN is a first-class, optional field: it is carried when an authoritative
source provides it and is never generated by this system.
"""

from __future__ import annotations

import datetime as _dt
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, field_validator


class SourceType(str, Enum):
    DRONE_IMAGERY = "drone_imagery"
    ORTHO_IMAGERY = "ortho_imagery"
    DSM = "dsm"
    DTM = "dtm"
    CADASTRAL_MAP = "cadastral_map"
    REVENUE_RECORD = "revenue_record"
    MUNICIPAL_GIS = "municipal_gis"
    UTILITY_NETWORK = "utility_network"
    GROUND_TRUTH = "ground_truth"
    GNSS_CORS = "gnss_cors"
    BUILDING_FOOTPRINT = "building_footprint"
    OTHER = "other"


class LandRecordAttributes(BaseModel):
    """Cadastral attributes available in the public training data.

    Owner names are deliberately absent: no model in this system performs
    owner-name matching.
    """

    village: str | None = None
    district: str | None = None
    state: str | None = None
    tehsil: str | None = None
    block: str | None = None
    pargana: str | None = None
    khasra: str | None = None
    khata: str | None = None
    survey_number: str | None = None
    village_code: str | None = None
    district_code: str | None = None
    parcel_type: str | None = None
    land_use: str | None = None
    area: float | None = Field(default=None, description="Area in area_unit")
    area_unit: str | None = None
    extra: dict[str, Any] = Field(default_factory=dict)

    def as_record(self) -> dict[str, Any]:
        payload = self.model_dump(exclude={"extra"}, exclude_none=True)
        payload.update(self.extra)
        return payload


class SourceRecord(BaseModel):
    """One record about a parcel as supplied by one source system."""

    source_system: str
    source_record_id: str
    source_type: SourceType = SourceType.OTHER
    source_parcel_id: str | None = None
    ulpin: str | None = None
    geometry: dict[str, Any] | None = Field(
        default=None, description="GeoJSON geometry in crs"
    )
    crs: str | None = None
    attributes: LandRecordAttributes = Field(default_factory=LandRecordAttributes)
    observed_at: _dt.datetime | None = None
    ingested_at: _dt.datetime = Field(
        default_factory=lambda: _dt.datetime.now(_dt.timezone.utc)
    )

    @field_validator("ulpin")
    @classmethod
    def _blank_ulpin_is_none(cls, value: str | None) -> str | None:
        if value is None:
            return None
        cleaned = value.strip()
        return cleaned or None


class CanonicalParcel(BaseModel):
    """A canonical parcel linking one or more source records."""

    parcel_id: str = Field(description="Internal canonical identifier")
    ulpin: str | None = Field(
        default=None,
        description="Authoritative ULPIN, only ever copied from a source record",
    )
    ulpin_source: str | None = None
    geometry: dict[str, Any] | None = None
    crs: str | None = None
    attributes: LandRecordAttributes = Field(default_factory=LandRecordAttributes)
    source_records: list[SourceRecord] = Field(default_factory=list)
    created_at: _dt.datetime = Field(
        default_factory=lambda: _dt.datetime.now(_dt.timezone.utc)
    )
    updated_at: _dt.datetime | None = None

    def link(self, record: SourceRecord) -> None:
        """Attach a source record, adopting its ULPIN when we have none."""

        self.source_records.append(record)
        if self.ulpin is None and record.ulpin:
            self.ulpin = record.ulpin
            self.ulpin_source = f"{record.source_system}:{record.source_record_id}"
        self.updated_at = _dt.datetime.now(_dt.timezone.utc)

    @property
    def source_keys(self) -> list[str]:
        return [
            f"{record.source_system}:{record.source_record_id}"
            for record in self.source_records
        ]

    def ulpin_disagreements(self) -> list[str]:
        values = {record.ulpin for record in self.source_records if record.ulpin}
        return sorted(values) if len(values) > 1 else []
